# Generated by Django 5.0.6 on 2024-05-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customerreview_alter_brand_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='comment',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='labels',
            field=models.CharField(choices=[('', 'default'), ('new', 'new'), ('sale', 'sale'), ('hot', 'hot')], max_length=50),
        ),
    ]
