# Generated by Django 5.0.6 on 2024-05-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_customerreview_comment_alter_product_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='rank',
            field=models.TextField(),
        ),
    ]
