# Generated by Django 5.0.6 on 2024-05-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_ad_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='rank',
            field=models.IntegerField(),
        ),
    ]
